import { jsPDF } from "jspdf";
import { toast } from "sonner";

export interface BriefData {
  id: number;
  keyword: string;
  title?: string;
  briefContent: string;
  createdAt: string;
}

/**
 * Export brief as PDF
 */
export const exportBriefAsPDF = (brief: BriefData) => {
  try {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    // Title
    doc.setFontSize(24);
    doc.setTextColor(88, 28, 135); // Purple
    const titleLines = doc.splitTextToSize(brief.title || brief.keyword, maxWidth);
    doc.text(titleLines, margin, yPosition);
    yPosition += titleLines.length * 10 + 5;

    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // Slate
    const date = new Date(brief.createdAt).toLocaleDateString();
    doc.text(`Keyword: ${brief.keyword}`, margin, yPosition);
    yPosition += 6;
    doc.text(`Generated: ${date}`, margin, yPosition);
    yPosition += 10;

    // Divider
    doc.setDrawColor(226, 232, 240); // Light slate
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;

    // Content
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42); // Dark slate
    const contentLines = doc.splitTextToSize(brief.briefContent, maxWidth);
    
    contentLines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += 6;
    });

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184); // Light slate
    doc.text("Generated by Clarity Engine", margin, pageHeight - 10);

    doc.save(`${brief.keyword}-brief.pdf`);
    toast.success("Brief exported as PDF");
  } catch (error) {
    console.error("PDF export error:", error);
    toast.error("Failed to export as PDF");
  }
};

/**
 * Export brief as Markdown
 */
export const exportBriefAsMarkdown = (brief: BriefData) => {
  try {
    const markdown = `# ${brief.title || brief.keyword}

**Keyword:** ${brief.keyword}  
**Generated:** ${new Date(brief.createdAt).toLocaleDateString()}

---

## Content Brief

${brief.briefContent}

---

*Generated by Clarity Engine*
`;

    const element = document.createElement("a");
    element.setAttribute("href", "data:text/markdown;charset=utf-8," + encodeURIComponent(markdown));
    element.setAttribute("download", `${brief.keyword}-brief.md`);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);

    toast.success("Brief exported as Markdown");
  } catch (error) {
    console.error("Markdown export error:", error);
    toast.error("Failed to export as Markdown");
  }
};

/**
 * Copy brief to clipboard
 */
export const copyBriefToClipboard = async (brief: BriefData) => {
  try {
    const text = `${brief.title || brief.keyword}\n\nKeyword: ${brief.keyword}\n\n${brief.briefContent}`;
    await navigator.clipboard.writeText(text);
    toast.success("Brief copied to clipboard");
  } catch (error) {
    console.error("Clipboard copy error:", error);
    toast.error("Failed to copy to clipboard");
  }
};

/**
 * Share brief as formatted text
 */
export const shareBriefAsText = (brief: BriefData) => {
  const text = `Check out this SEO content brief for "${brief.keyword}" generated by Clarity Engine: ${brief.title || brief.keyword}`;
  
  if (navigator.share) {
    navigator.share({
      title: brief.title || brief.keyword,
      text: text,
    }).catch(err => console.error("Share error:", err));
  } else {
    copyBriefToClipboard(brief);
  }
};
