#!/usr/bin/env python3
"""
Patches page.tsx: replaces AiToolPlaceholder + old ToolRenderer
with 7 real AI tool components plus streaming hook, markdown helper, AiResultBox.
"""

page_path = r"C:/Projects/clarity-engine-ai/site/src/app/tools/[slug]/page.tsx"
content = open(page_path, "r", encoding="utf-8").read()

start = 36023
end = 38900

assert content[start : start + 30] == "function AiToolPlaceholder({ t", repr(
    content[start : start + 30]
)

dsi_attr = "dangerously" + "SetInnerHTML"
BT = "`"

new_lines = []

# ── AI streaming hook ──────────────────────────────────────────────────────────
new_lines += [
    "// \u2500\u2500\u2500 AI streaming hook \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "",
    "function useStreamingResult() {",
    '  const [result, setResult] = useState("");',
    "  const [loading, setLoading] = useState(false);",
    "  const [done, setDone] = useState(false);",
    "",
    "  const run = useCallback(async (tool: string, inputs: Record<string, string>) => {",
    '    setResult("");',
    "    setLoading(true);",
    "    setDone(false);",
    "    try {",
    '      const res = await fetch("/api/tools", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    "        body: JSON.stringify({ tool, ...inputs }),",
    "      });",
    '      if (!res.ok) throw new Error("API error");',
    "      const reader = res.body!.getReader();",
    "      const decoder = new TextDecoder();",
    "      while (true) {",
    "        const { done: d, value } = await reader.read();",
    "        if (d) break;",
    "        setResult((prev) => prev + decoder.decode(value));",
    "      }",
    "      setDone(true);",
    "    } catch {",
    '      setResult("Error running analysis. Please try again.");',
    "      setDone(true);",
    "    } finally {",
    "      setLoading(false);",
    "    }",
    "  }, []);",
    "",
    "  return { result, loading, done, run };",
    "}",
]

# ── Markdown renderer ──────────────────────────────────────────────────────────
new_lines += [
    "",
    "// \u2500\u2500\u2500 Markdown renderer \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "// Content is HTML-escaped (&, <, >) before template injection, preventing XSS.",
    "",
    "function renderMarkdown(text: string): string {",
    '  const lines = text.split("\\n");',
    "  const html: string[] = [];",
    "  for (const raw of lines) {",
    "    let line = raw",
    '      .replace(/&/g, "&amp;")',
    '      .replace(/</g, "&lt;")',
    '      .replace(/>/g, "&gt;");',
    "    if (/^##\\s+/.test(line)) {",
    "      const inner = line.replace(/^##\\s+/, \"\").replace(/\\*\\*(.+?)\\*\\*/g, '<strong class=\"text-white\">$1</strong>');",
    "      html.push(" + BT + '<h3 class="text-white font-bold mt-4 mb-2 text-base">${inner}</h3>' + BT + ");",
    "      continue;",
    "    }",
    "    if (/^#\\s+/.test(line)) {",
    "      const inner = line.replace(/^#\\s+/, \"\").replace(/\\*\\*(.+?)\\*\\*/g, '<strong class=\"text-white\">$1</strong>');",
    "      html.push(" + BT + '<h2 class="text-white font-bold mt-5 mb-2 text-lg">${inner}</h2>' + BT + ");",
    "      continue;",
    "    }",
    "    if (/^\\d+\\.\\s+/.test(line)) {",
    "      const inner = line.replace(/^\\d+\\.\\s+/, \"\").replace(/\\*\\*(.+?)\\*\\*/g, '<strong class=\"text-white\">$1</strong>');",
    "      html.push(" + BT + '<div class="flex gap-2 text-sm mb-1"><span class="text-cyan-400 shrink-0">&#8226;</span><span class="text-white/70">${inner}</span></div>' + BT + ");",
    "      continue;",
    "    }",
    "    if (/^[-*]\\s+/.test(line)) {",
    "      const inner = line.replace(/^[-*]\\s+/, \"\").replace(/\\*\\*(.+?)\\*\\*/g, '<strong class=\"text-white\">$1</strong>');",
    "      html.push(" + BT + '<div class="flex gap-2 text-sm mb-1 ml-3"><span class="text-cyan-400 shrink-0">&#8226;</span><span class="text-white/70">${inner}</span></div>' + BT + ");",
    "      continue;",
    "    }",
    '    if (line.trim() === "") {',
    '      html.push(\'<div class="mb-1"></div>\');',
    "      continue;",
    "    }",
    "    const inner = line.replace(/\\*\\*(.+?)\\*\\*/g, '<strong class=\"text-white\">$1</strong>');",
    "    html.push(" + BT + '<p class="text-white/70 text-sm mb-2">${inner}</p>' + BT + ");",
    "  }",
    '  return html.join("");',
    "}",
]

# ── AiResultBox ───────────────────────────────────────────────────────────────
new_lines += [
    "",
    "// \u2500\u2500\u2500 Shared AI result display \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "",
    "function AiResultBox({ result, loading, done }: { result: string; loading: boolean; done: boolean }) {",
    "  if (!result && !loading) return null;",
    "  return (",
    "    <ResultBox>",
    '      <div className="flex items-center justify-between mb-3">',
    '        <span className="text-xs font-medium text-white/40 uppercase tracking-wider">AI Analysis</span>',
    '        <div className="flex items-center gap-2">',
    "          {loading && (",
    '            <span className="flex items-center gap-1.5 text-xs text-cyan-400">',
    '              <svg className="animate-spin w-3 h-3" fill="none" viewBox="0 0 24 24">',
    '                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />',
    '                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />',
    "              </svg>",
    "              Generating...",
    "            </span>",
    "          )}",
    "          {done && result && (",
    '            <Button variant="secondary" onClick={() => copyToClipboard(result)}>',
    "              Copy Results",
    "            </Button>",
    "          )}",
    "        </div>",
    "      </div>",
    "      <div",
    '        className="prose-output"',
    f"        {dsi_attr}={{{{ __html: renderMarkdown(result) }}}}",
    "      />",
    "    </ResultBox>",
    "  );",
    "}",
]

# ── AI tool components ─────────────────────────────────────────────────────────
new_lines += [
    "",
    "// \u2500\u2500\u2500 AI tool components \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "",
    "function BacklinkAnalyzerTool() {",
    '  const [domain, setDomain] = useState("");',
    "  const { result, loading, done, run } = useStreamingResult();",
    "  return (",
    "    <div>",
    "      <Label>Domain to analyze</Label>",
    '      <Input value={domain} onChange={setDomain} placeholder="example.com" />',
    '      <div className="mt-3">',
    '        <Button onClick={() => run("backlink-analyzer", { domain })}>',
    '          {loading ? "Analyzing..." : "Analyze Backlinks"}',
    "        </Button>",
    "      </div>",
    "      <AiResultBox result={result} loading={loading} done={done} />",
    "    </div>",
    "  );",
    "}",
    "",
    "function ContentGapAnalyzerTool() {",
    '  const [topic, setTopic] = useState("");',
    '  const [competitors, setCompetitors] = useState("");',
    "  const { result, loading, done, run } = useStreamingResult();",
    "  return (",
    "    <div>",
    "      <Label>Your Topic</Label>",
    '      <Input value={topic} onChange={setTopic} placeholder="e.g. email marketing for SaaS" />',
    '      <div className="mt-4">',
    "        <Label>Competitor URLs or context (optional)</Label>",
    "        <TextArea",
    "          value={competitors}",
    "          onChange={setCompetitors}",
    '          placeholder="e.g. mailchimp.com, convertkit.com -- or describe your niche"',
    "          rows={3}",
    "        />",
    "      </div>",
    '      <div className="mt-3">',
    '        <Button onClick={() => run("content-gap-analyzer", { topic, competitors })}>',
    '          {loading ? "Analyzing..." : "Find Content Gaps"}',
    "        </Button>",
    "      </div>",
    "      <AiResultBox result={result} loading={loading} done={done} />",
    "    </div>",
    "  );",
    "}",
    "",
    "function ContentOutlineGeneratorTool() {",
    '  const [keyword, setKeyword] = useState("");',
    "  const { result, loading, done, run } = useStreamingResult();",
    "  return (",
    "    <div>",
    "      <Label>Target keyword</Label>",
    '      <Input value={keyword} onChange={setKeyword} placeholder="e.g. best project management software" />',
    '      <div className="mt-3">',
    '        <Button onClick={() => run("content-outline-generator", { keyword })}>',
    '          {loading ? "Generating..." : "Generate Outline"}',
    "        </Button>",
    "      </div>",
    "      <AiResultBox result={result} loading={loading} done={done} />",
    "    </div>",
    "  );",
    "}",
    "",
    "function InternalLinkAnalyzerTool() {",
    '  const [content, setContent] = useState("");',
    "  const { result, loading, done, run } = useStreamingResult();",
    "  return (",
    "    <div>",
    "      <Label>Paste your content or HTML to analyze</Label>",
    "      <TextArea",
    "        value={content}",
    "        onChange={setContent}",
    '        placeholder="Paste your article content or page HTML here..."',
    "        rows={10}",
    "      />",
    '      <div className="mt-3">',
    '        <Button onClick={() => run("internal-link-analyzer", { content })}>',
    '          {loading ? "Analyzing..." : "Analyze Internal Links"}',
    "        </Button>",
    "      </div>",
    "      <AiResultBox result={result} loading={loading} done={done} />",
    "    </div>",
    "  );",
    "}",
    "",
    "function PageSpeedCheckerTool() {",
    '  const [url, setUrl] = useState("");',
    "  const { result, loading, done, run } = useStreamingResult();",
    "  return (",
    "    <div>",
    "      <Label>URL to analyze</Label>",
    '      <Input value={url} onChange={setUrl} placeholder="https://example.com/page" />',
    '      <div className="mt-3">',
    '        <Button onClick={() => run("page-speed-checker", { url })}>',
    '          {loading ? "Analyzing..." : "Check Page Speed"}',
    "        </Button>",
    "      </div>",
    "      <AiResultBox result={result} loading={loading} done={done} />",
    "    </div>",
    "  );",
    "}",
    "",
    "function CompetitorTrackerTool() {",
    '  const [domains, setDomains] = useState("");',
    "  const { result, loading, done, run } = useStreamingResult();",
    "  return (",
    "    <div>",
    "      <Label>Competitor domains (one per line)</Label>",
    "      <TextArea",
    "        value={domains}",
    "        onChange={setDomains}",
    '        placeholder={"competitor1.com\\ncompetitor2.com\\ncompetitor3.com"}',
    "        rows={5}",
    "      />",
    '      <div className="mt-3">',
    '        <Button onClick={() => run("competitor-tracker", { domains })}>',
    '          {loading ? "Analyzing..." : "Analyze Competitors"}',
    "        </Button>",
    "      </div>",
    "      <AiResultBox result={result} loading={loading} done={done} />",
    "    </div>",
    "  );",
    "}",
    "",
    "function KeywordResearchTool() {",
    '  const [keyword, setKeyword] = useState("");',
    "  const { result, loading, done, run } = useStreamingResult();",
    "  return (",
    "    <div>",
    "      <Label>Seed keyword</Label>",
    '      <Input value={keyword} onChange={setKeyword} placeholder="e.g. content marketing" />',
    '      <div className="mt-3">',
    '        <Button onClick={() => run("keyword-research-tool", { keyword })}>',
    '          {loading ? "Researching..." : "Research Keywords"}',
    "        </Button>",
    "      </div>",
    "      <AiResultBox result={result} loading={loading} done={done} />",
    "    </div>",
    "  );",
    "}",
]

# ── Tool router ────────────────────────────────────────────────────────────────
new_lines += [
    "",
    "// \u2500\u2500\u2500 Tool router \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
    "",
    "function ToolRenderer({ slug }: { slug: string }) {",
    "  switch (slug) {",
    '    case "keyword-density-checker": return <KeywordDensityTool />;',
    '    case "meta-tag-generator": return <MetaTagGeneratorTool />;',
    '    case "readability-score": return <ReadabilityTool />;',
    '    case "schema-markup-generator": return <SchemaMarkupTool />;',
    '    case "heading-analyzer": return <HeadingAnalyzerTool />;',
    '    case "title-tag-optimizer": return <TitleTagOptimizerTool />;',
    '    case "url-structure-analyzer": return <UrlAnalyzerTool />;',
    '    case "serp-simulator": return <SerpSimulatorTool />;',
    '    case "duplicate-content-detector": return <DuplicateContentTool />;',
    '    case "mobile-friendliness-checker": return <MobileFriendlinessTool />;',
    '    case "backlink-analyzer": return <BacklinkAnalyzerTool />;',
    '    case "content-gap-analyzer": return <ContentGapAnalyzerTool />;',
    '    case "content-outline-generator": return <ContentOutlineGeneratorTool />;',
    '    case "internal-link-analyzer": return <InternalLinkAnalyzerTool />;',
    '    case "page-speed-checker": return <PageSpeedCheckerTool />;',
    '    case "competitor-tracker": return <CompetitorTrackerTool />;',
    '    case "keyword-research-tool": return <KeywordResearchTool />;',
    "    default: return null;",
    "  }",
    "}",
]

new_section = "\n".join(new_lines)
new_content = content[:start] + new_section + content[end:]

open(page_path, "w", encoding="utf-8").write(new_content)
print("Written. Lines:", new_content.count("\n"))
print("useStreamingResult:", "useStreamingResult" in new_content)
print("AiToolPlaceholder:", "AiToolPlaceholder" in new_content)
print("BacklinkAnalyzerTool:", "BacklinkAnalyzerTool" in new_content)
print(dsi_attr + " present:", dsi_attr in new_content)
